// SPDX-FileCopyrightText: Copyright (c) 2025 Space Wizards Federation
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Common.AgeGate;

[GenerateTypedNameReferences]
public sealed partial class AgeGatePopup : Control
{
    public int MinimumAgeInYears = 18;

    public event Action? OnQuitPressed;
    public event Action? OnAgeGatePassed;
    public event Action? OnAgeGateGated;

    /// <summary>
    /// The date currently selected by the input, or null if it's not a valid date.
    /// </summary>
    public DateTime? SelectedDate = null;

    public AgeGatePopup()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += OnAcceptButtonPressed;
        QuitButton.OnPressed += OnQuitButtonPressed;

        DobMonthOptionButton.AddItem(Loc.GetString("datepicker-month"), 0);
        for (var i = 1; i <= 12; i++)
        {
            DobMonthOptionButton.AddItem(Loc.GetString($"month-{i}"), i);
        }

        DobDayLineEdit.OnTextChanged += _ => UpdateInput();
        DobYearLineEdit.OnTextChanged += _ => UpdateInput();
        DobMonthOptionButton.OnItemSelected += args => {
            if (args.Id != 0)
            {
                DobMonthOptionButton.SelectId(args.Id);
            }
            UpdateInput();
        };

    }

    private void UpdateInput()
    {
        var monthNum = DobMonthOptionButton.SelectedId;
        if (uint.TryParse(DobYearLineEdit.Text, out uint year)
            && year > 1900
            && uint.TryParse(DobDayLineEdit.Text, out uint day)
            && monthNum != 0
            && DateTime.TryParse($"{year}-{monthNum:00}-{day:00}", null, System.Globalization.DateTimeStyles.RoundtripKind, out var date))
        {
            SelectedDate = date;
            AcceptButton.Disabled = false;
        }
        else
        {
            SelectedDate = null;
            AcceptButton.Disabled = true;
        }
    }

    private void OnQuitButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        OnQuitPressed?.Invoke();
    }

    private void OnAcceptButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (SelectedDate is null)
            return;

        var today = DateTime.Today;
        int yearDiff = today.Year - SelectedDate.Value.Year;
        int age = SelectedDate.Value.Date > today.AddYears(-yearDiff)
            ? yearDiff - 1
            : yearDiff;

        if (age < MinimumAgeInYears)
        {
            OnAgeGateGated?.Invoke();
        }
        else
        {
            OnAgeGatePassed?.Invoke();
        }
    }
}
