// <auto-generated />
using System;
using System.Collections.Generic;
using Content.Server.Database._Citadel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Content.Server.Database.Migrations._Citadel.Postgres
{
    [DbContext(typeof(CitadelPostgresContext))]
    [Migration("20251008131009_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("citadel")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Content.Server.Database._Citadel.Model.Dto.PlayerDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_player");

                    b.ToTable("player", "ss14", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Content.Server.Database._Citadel.Model.Persistence.PersistedWorldObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("persisted_world_objects_id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.PrimitiveCollection<List<string>>("Notes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("notes");

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("true_name");

                    b.HasKey("Id")
                        .HasName("PK_persisted_world_objects");

                    b.ToTable("persisted_world_objects", "citadel");

                    b.HasDiscriminator().HasValue("PersistedWorldObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Content.Server.Database._Citadel.Model.Persistence.PersistedCharacter", b =>
                {
                    b.HasBaseType("Content.Server.Database._Citadel.Model.Persistence.PersistedWorldObject");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer")
                        .HasColumnName("death_count");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasIndex("PlayerId");

                    b.HasDiscriminator().HasValue("PersistedCharacter");
                });

            modelBuilder.Entity("Content.Server.Database._Citadel.Model.Persistence.PersistedCharacter", b =>
                {
                    b.HasOne("Content.Server.Database._Citadel.Model.Dto.PlayerDto", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .HasConstraintName("FK_persisted_world_objects_player_player_id");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
